# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f26c05a5e4b445eaab06e963fbbc7d6cea7c9aca26bf538ba8d3e37b52ac2843a6223b5cf5e3d3d9fb0b03046c96b8827820de0ee619ec5a774f311b03c30cb

test:
  secret_key_base: 41ac0bef8e6fe7026f7c8b130f2eb301911b4cd0c4ce94d8c7d420c3a6ffc2838229de335b8851b796daedd5f312ce25cc3752c53be2747560917effed8a492c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
